config/routes.rb
Rails.application.routes.draw do
    root 'posts#index'
    resources :posts
    resources :categories
  
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence:true
    has_many :posts, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
    validates_presence_of :title, :body, :category_id
    belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @category_posts = @category.posts
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(permit_params)
    if @category.save
      redirect_to categories_path, :notice => "You just created a new category"
    else
      render "new", :notice => "Your category WAS NOT created"
    end
    
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(permit_params)
      redirect_to categories_path, :notice => "The category was updated"
    else
      render "edit", :notice => "Your category WAS NOT updated"
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy      
    redirect_to categories_path, :notice => "Your category and all of its associated posts have been deleted"       
  end
  
  private

  def permit_params
    params.require(:category).permit(:name)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(permit_params)
    if @post.save
      redirect_to root_path, :notice => "Your post was saved"
    else
      render "new", :alert => "Your post WAS NOT saved"
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(permit_params)
      redirect_to post_path, :notice => "Your post was updated"
    else
      render "edit", :notice => "Your post WAS NOT updated"
    end

  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, :alert => 'Your post has been deleted.'
  end
  
  private 

    def permit_params
      params.require(:post).permit(:title, :body, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/edit.html.erb
<div class="container">
    <h1><strong>Edit category</strong></h1>
    <br/>
    <%= form_for @category do |c|%>
        <p>
            <%= c.label :name %> <br/>
            <%= c.text_field :name %> <br/>
        </p>
        <p>
            <%= c.submit "Edit Category"%>
        </p>
    <% end %>
    
</div>

app/views/categories/index.html.erb
<div class="container column is-12">
    <h3><strong>Listing the most recent 12 categories:</strong></h3><br/>

    <!-- With columns, no groups needed -->
    <div class="columns is-multiline">
        <% @categories.last(12).each do |cat| %>
            <div class="column is-one-third">
                <article class="notification is-info">
                    <p class="has-text-centered"><%= link_to cat.name, cat %></p>
                </article>
            </div>
        <% end %>
    </div>

    <div class="card">
        <div class="card-content">
            <h5 class="title is-5">Card and fa icons testing<h3>
            <h5 class="subtitle is-5">Subtitle<h3>
        </div>
        <footer class="card-footer">
            <div class="card-footer-item">
                <a href="#" class="button is-success"><i class="fa fa-thumbs-o-up"></i></a>
            </div>
            <div class="card-footer-item">
                <a href="#" class="button"><i class="fa fa-bell"></i></a>
            </div>
            <div class="card-footer-item">
                <a href="#" class="button"><i class="fa fa-gem"></i></a>
            </div>
                <div>
                    <span class="icon">
                        <i class="fas fa-home"></i>
                    </span>
                    <span class="icon has-text-info">
                        <i class="fa fa-info-circle"></i>
                    </span>
                    <span class="icon has-text-success">
                        <i class="fa fa-check-square"></i>
                    </span>
                    <span class="icon has-text-warning">
                        <i class="fa fa-exclamation-triangle"></i>
                    </span>
                    <span class="icon has-text-danger">
                        <i class="fa fa-ban"></i>
                    </span>
                    <span class="icon">
                        <i class="fa fa-atom"></i>
                    </span>
                    <span class="icon has-text-danger">
                        <i class="fab fa-battle-net"></i>
                    </span>
                </div>
            </div>
        </footer>
    </div> <br />

    <button class="button is-medium is-transparent has-text-weight-bold">
        <%= link_to "Create new category", new_category_path %>
    </button>
  
</div> 

app/views/categories/new.html.erb
<div class="container">
    <h1><strong>Create a new category</strong></h1>
    <br/>
    <%= form_for @category do |c|%>
        <p>
            <%= c.label :name %> <br/>
            <%= c.text_field :name %> <br/>
        </p>
        <p>
            <%= c.submit "Create Category"%>
        </p>
    <% end %>
    
</div>

app/views/categories/show.html.erb
<div class="container">

    <p><strong>All existing posts in "<%= @category.name %>"</strong>:</p>
    <% if @category_posts.empty? %>
        <p><%= "Sorry, there are no posts in this category" %></p> 
    <% else %>
        <ul>
            <% @category_posts.each do |cat_post|%>
            <li><%= link_to cat_post.title, cat_post %></li>
            <% end %>
        </ul>
    <% end %>
    <br/>
    <p> <%= link_to "Edit #{@category.name}", edit_category_path %> | <%= link_to "Delete #{ @category.name }", @category, data: { confirm: "Delete the whole category? Are you sure?" }, :method => :delete %> </p>
    
</div>

app/views/layouts/_aside_left.html.erb
<aside class="menu">
    <p class="menu-label">General</p>
    <ul class="menu-list">
        <li><a>Dashboard</a></li>
        <li><a>Customers</a></li>
    </ul>
    <p class="menu-label">Administration</p>
    <ul class="menu-list">
        <li><a>Team Settings</a></li>
        <li>
        <a class="is-active">Manage Your Team</a>
        <ul>
            <li><a>Members</a></li>
            <li><a>Plugins</a></li>
            <li><a>Add a member</a></li>
        </ul>
        </li>
        <li><a>Invitations</a></li>
        <li><a>Cloud Storage Environment Settings</a></li>
        <li><a>Authentication</a></li>
    </ul>
    <p class="menu-label">Transactions</p>
    <ul class="menu-list">
        <li><a>Payments</a></li>
        <li><a>Transfers</a></li>
        <li><a>Balance</a></li>
    </ul>
</aside>

app/views/layouts/_footer.html.erb
<footer class="container notification is-dark has-text-centered">
        
    <h3 class="subtitle is-5">The Footer</h3>

    <div class="columns">       
        <div class="column">
            <ul>
                <li>First</li>
                <li>Second</li>
                <li>Third</li>
                <li>Fourth</li>
            </ul>
        </div>

        <div class="column">
            <ul>
                <li>First</li>
                <li>Second</li>
                <li>Third</li>
                <li>Fourth</li>
            </ul>
        </div>

        <div class="column">
            <ul>
                <li>First</li>
                <li>Second</li>
                <li>Third</li>
                <li>Fourth</li>
            </ul>
        </div>

        <div class="column">
            <ul>
                <li>First</li>
                <li>Second</li>
                <li>Third</li>
                <li>Fourth</li>
            </ul>
        </div>
    </div>
    
</footer>

app/views/layouts/_header.html.erb
<header class="container">
  <nav class="navbar" role="navigation" aria-label="main navigation">

    <div class="navbar-brand">
    <a class="navbar-item" href="#">
        <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
      </a>
      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div class="navbar-menu" id="navbarBasicExample" >        
      <div class="navbar-start">
          <div class="navbar-item" >
              <%= link_to "Posts", posts_path %>
          </div>
          <div class="navbar-item" >
              <%= link_to "Categories", categories_path %>
          </div>

          <div class="navbar-item field has-addons">
              <div class="control">
                  <input class="input" type="text" placeholder="Search">
              </div>
              <div class="control">
                  <a class="button is-info">Search</a>
              </div>
          </div>
      </div>

      <div class="navbar-end">
          <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link">More</a>
              <div class="navbar-dropdown">
                  <a class="navbar-item">About</a>
                  <a class="navbar-item">Contact</a>
                  <hr class="navbar-divider">
                  <a class="navbar-item">Report an issue</a>
              </div>
          </div>
  
        <div class="navbar-item">
          <div class="buttons">
            <a class="button is-primary"><strong>Sign up</strong></a>
            <a class="button is-light">Log in</a>
          </div>
        </div>
      </div>
    </div>
    
  </nav>
</header>

app/views/layouts/_notices_alerts.html.erb
<% flash.each do |key, value| %>
    <% key == 'notice' ? key = "success" : key = "danger" %>
    <div class="message is-<%= key %> has-text-centered is-marginless" id="flashMessage">
        <div class="message-body is-borderless">       
        <%= value %>
        <button class="delete" aria-label="delete" id="deleteFlashMessage"></button>
        </div>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp1b</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/notices_alerts' %>

    <section class="section">
      <%= render "layouts/header" %><br/>
    </section>
    
    <section class="section">
      <div class="container">
        <div class="columns">

          <div class="column is-2">
            <%= render "layouts/aside_left" %>
          </div>
                      
          <div class="column is-10">
            <main>
              <%= yield %>
            </main>
          </div>
          
        </div>
      </div>
    </section>
      
    <section class="section">
      <%= render "layouts/footer" %>
    </section>

  </body>
</html>

app/views/posts/edit.html.erb
<div class="container">
    <h1><strong>Edit post</strong></h1>
    <br/>
    <%= form_for @post do |f|%>
        <p>
            <%= f.label :title %> <br/>
            <%= f.text_field :title %> <br/>
        </p>
        <p>
            <%= f.label :body%> <br/>
            <%= f.text_area :body %> <br/>
        </p>
        <p>
            <%= f.label :category_id %> <br/>
            <%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]} %>
        </p>
        <br/>
        <p>
            <%= f.submit "Update Post"%>
        </p>
        <br/>
        <%= link_to "Go Back", post_path %>

    <% end %>
</div>

app/views/posts/new.html.erb
<div class="container">

    <h1><strong>Create a new post</strong></h1>
    <br/>
    <%= form_for @post do |f| %>
        <p>
            <%= f.label :title %> <br/>
            <%= f.text_field :title %> <br/>
        </p>
        <p>
            <%= f.label :body%> <br/>
            <%= f.text_area :body %> <br/>
        </p>
        <p>
            <%= f.label :category_id %> <br/>
            <%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]} %>
        </p>
        <br/>
        <p>
            <%= f.submit "Create Post" %>
        </p>
    <% end %>
    
</div>

app/views/posts/show.html.erb
<div class="container">
    <div class="container">
        <h2><strong><%= @post.title %></strong></h1>    
        <p><small><%= @post.created_at.strftime("%b %d, %Y") %></small></p><br />
    </div>
    <div class="container">
        <p><%= @post.body %></p><br />
        <p><%= @post.title %> category: <%= link_to @post.category.name, category_path(:id  => @post.category.id) %></p><br />
    </div>
    <p><%= link_to "Edit Post", edit_post_path %> | <%= link_to "Delete Post", @post, data: { confirm: 'Delete? Are you sure?' }, :method => :delete %></p>
    
</div>